version: '3.9'

networks:
  ros:
    driver: bridge

services:
  530-master:
    image: rob530_project
    entrypoint: /bin/zsh 
    command: -c "source /opt/ros/noetic/setup.zsh && stdbuf -o L roscore"
    networks:
      - ros
    restart: always
    container_name: 530-master


  project:
    image: deep_svo/devel
    # depends_on:
    #    - 530-master
    container_name: project
    networks:
      - ros
    environment:
      - "DISPLAY=${DISPLAY}"
      - "QT_GRAPHICSSYSTEM=native"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
      - "TERM=xterm-256color"
      - "XAUTHORITY"
      - "--gpus=all"
    working_dir: "/root/ws/"
    privileged: true
    devices:
      - /dev/nvidia0
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /home/luke/Documents/Academic/535/proj/deep-svo:/root/ws/
      - /home/luke/Documents/Academic/535/proj/data:/root/ws/rosbag/
      - .bashrc:/root/.bashrc:rw

    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    entrypoint: /bin/bash
